### ISSUE TITLE
Multiuser/permissions support

### ISSUE THREAD

**Issue by dsheets** [mit-pdos/fscq#10]
Some security properties of some systems are, at least partially, reliant on file system support for `rwx` permissions for users, groups, and 'other'. These features are often used in conjunction with multiuser access to a single mounted file system and FS enforcement of user permission policy.

**Comment by tchajed** [comment]
We wrote a paper on this (see the [security branch](https://github.com/mit-pdos/fscq/tree/security) for the code), and while full support for POSIX permissions is incomplete in that version I think it's a pretty good effort.
