### ISSUE TITLE
Removing a non-empty directory results in EIO

### ISSUE THREAD

**Issue by dsheets** [mit-pdos/fscq#3]
On 27c4078, running

```
$ mkdir foo
$ touch foo/bar
$ rmdir foo
```

results in `rmdir: failed to remove ‘foo’: Input/output error` when either `EEXIST` or `ENOTEMPTY` is expected in this case. See http://pubs.opengroup.org/onlinepubs/9699919799/functions/rmdir.html for details.

**Comment by zeldovich** [comment]
Thanks; you are absolutely correct that this is a bug and it would be good to fix.  At the moment, neither fscq's implementation nor theorems attempt to return the right errno values (e.g., see our SOSP paper's eval section); almost every system call likely returns the wrong errnos.

**Comment by dsheets** [comment]
Most of the errnos look correct/reasonable, actually. The only ones that we picked up are related to directory removal and renaming. Would you like me to file the other errno issue or leave it here?

I also have an nlink issue and a number of known unsupported feature issues. Would you like them filed or sent somewhere or dropped?

**Comment by tchajed** [comment]
This issue turns out to be fixed in FSCQ, which now propagates error codes at least in some cases.
