### ISSUE TITLE
chmod has no effect and does not return an error

### ISSUE THREAD

**Issue by dsheets** [mit-pdos/fscq#5]
On 27c4078a00b517671163f668ebd644614171d966, when running:

```
# touch foo
# ls -l foo
-rwxrwxrwx 1 root root 0 Jan  1  1970 foo
# chmod 700 foo
# ls -l foo
-rwxrwxrwx 1 root root 0 Jan  1  1970 foo
```

an error such as `ENOSYS` is expected if `chmod` is not implemented.

**Comment by zeldovich** [comment]
Pragmatically, this is because we do not handle permissions in the code/theorems, but some applications fail unnecessarily if chmod returns an error.  (You are of course correct that this is not legal as far as POSIX goes.)

**Comment by dsheets** [comment]
Yes, that makes sense. This is perhaps subsumed by #10.
