### ISSUE TITLE
Renaming a directory to a non-empty directory results in EIO

### ISSUE THREAD

**Issue by dsheets** [mit-pdos/fscq#6]
On 27c4078a00b517671163f668ebd644614171d966, running

``` c
#include <stdio.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>

int main() {
  int err;

  mkdir("a", 0700);
  mkdir("b", 0700);
  mkdir("b/0",0);
  errno = 0;
  err = rename("a","b");
  if (err < 0) {
    printf("rename error: %s\n",strerror(errno));
    return 1;
  }

  return 0;
}
```

prints `rename error: Input/output error` when the `rename` call should set `errno` to `ENOTEMPTY` or `EEXIST`. This issue is probably related to #3 and approximately as unlikely cause significant issues for applications.

**Comment by tchajed** [comment]
This issue turns out to be fixed in FSCQ, which now propagates error codes at least in some cases.
